import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "IWS Online School",
  description: "Generated by create next app ",
  abstract: "A brief description of what this web-page is about. Not recommended, superseded by description.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
    {children}
  </section>
  );
}
